on:
  push:
    branches: ["main"]
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - "**.rs"
      - "**.wit"

jobs:
  publish:
    uses: wasco-dev/workflows/.github/workflows/publish-wasm.yml@main
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    secrets: inherit
